export default [
  {
    label:'协作概况',
    icon:'ios-stats',
    name:'overview',
  },
  {
    label:'任务管理',
    icon:'ios-list-box',
    name:'taskManagement',
    child:[
      {
        label:'流程1',
        name:'taskManagement?id=x'
      },
      {
        label:'流程2',
        name:'taskManagement?id=xx'
      },
      {
        label:'流程3',
        name:'taskManagement?id=xxx',
        child:[
          {
            label:'节点1',
            name:'taskManagement?id=xxxx'
          }
        ]
      }
    ]
  },
  {
    label:'模板管理',
    icon:'md-paper',
    name:'templateManagement',
  },
  {
    label:'流程管理',
    icon:'md-film',
    name:'processManagement',
  },
  {
    label:'字典管理',
    icon:'ios-book',
    name:'dictionaryManagement',
  },
  {
    label:'编码规则',
    icon:'ios-keypad',
    name:'codingRules',
  },
]